server:
  port: 8191


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ivandemydko/config-store
          search-paths:
#           - 'service-config/*service'
           - '*service'
          #username: root
          #passphrase: 12345

